{{ config(schema='staging') }}

SELECT 
    TRIPDURATION AS TRIP_DURATION,
	STARTTIME AS START_TIME,
	STOPTIME AS STOP_TIME,
	START_STATION_ID,
	START_STATION_NAME,
	START_STATION_LATITUDE,
	START_STATION_LONGITUDE,
	END_STATION_ID,
	END_STATION_NAME,
	END_STATION_LATITUDE,
	END_STATION_LONGITUDE,
	BIKEID,
	RIDER_PLAN,
	USERTYPE,
	BIRTH_YEAR,
	GENDER,
    CAST(STARTTIME AS DATE) AS start_date,
    ROUND(TRIPDURATION / 60.0, 0) AS trip_minutes,
    TO_CHAR(start_date, 'YYYY-MM') AS month,
    CASE 
        WHEN MONTH(start_date) BETWEEN 3 AND 5 THEN 'Spring'
        WHEN MONTH(start_date) BETWEEN 6 AND 8 THEN 'Summer'
        WHEN MONTH(start_date) BETWEEN 9 AND 11 THEN 'Fall'
        ELSE 'Winter'  -- Covers Dec, Jan, Feb
    END AS season
FROM {{source('STG_SOURCE','RAW_CITIBIKE')}}